[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --cov=. --cov-config=.coveragerc --cov-report=xml --cov-report=term-missing:skip-covered
